### ISSUE TITLE
error when launching the command

### ISSUE THREAD

**Issue by MisterM74** [nbs-system/naxsi#144]
nxtool.py -c /usr/local/etc/nxapi.json -x --colors
# size :1000
# Whitelist(ing) ratio :

No handlers could be found for logger "elasticsearch"
Traceback (most recent call last):
  File "/usr/local/bin/nxtool.py", line 224, in <module>
    translate.fetch_top(cfg.cfg["global_filters"], "whitelisted", limit=2)
  File "/usr/local/lib/python2.7/dist-packages/nxapi/nxtransform.py", line 519, in fetch_top
    res = self.search(esq)
  File "/usr/local/lib/python2.7/dist-packages/nxapi/nxtransform.py", line 550, in search
    x = self.es.search(index=self.cfg["elastic"]["index"], doc_type=self.cfg["elastic"]["doctype"], body=esq)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(_args, params=params, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 440, in search
    params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 284, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 55, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 97, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, u'IndexMissingException[[nxapi] missing]')

**Comment by StefanCG** [comment]
Hey guys,

I've just setup ES according to the readme and in fact I'm able to push data towards ES with nxtool.

But when running 
`nxtool.py -c nxapi.json -x`

I get the same error the OP reported above. And in my case the data is obviously being stored in teh index.

`curl -XPOST "http://127.0.0.1:9200/nxapi/events/_search?pretty" -d '{}'                
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 158,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "nxapi",
      "_type" : "events",
      "_id" : "AC3IzdshFCDWPC0DWib1",
      "_score" : 1.0,
      "_source":{}
    }, {
      "_index" : "nxapi",
      "_type" : "events",
...`


Can you please advise? I'm not a python guy as all so I'm somewhat lost as I just want to create a really tiny whitelist ...

PS: I'm using the most recent version (just cloned from git)
