### ISSUE TITLE
Infinite loop when tagging whitelists

### ISSUE THREAD

**Issue by lookingcloudy** [nbs-system/naxsi#281]
I notice a prior issue that has been fixed.  I just downloaded and compiled this a couple weeks ago. I'm getting infinite loop when tagging. After a few minutes I exited...here is the stack:

```python
Tagged 0 events out of 1
Tagged 0 events out of 1
Tagged 0 events out of 1
Tagged 0 events out of 1
Tagged 0 events out of 1
Tagged 0 events out of 1
Tagged 0 events out of 1
^CTraceback (most recent call last):
  File "./nxtool.py", line 233, in <module>
    x = translate.tag_events(esq, "Whitelisted", tag=options.tag)
  File "/usr/src/nginx/naxsi-0.55rc1/nxapi/nxapi/nxtransform.py", line 655, in tag_events
    res = self.search(esq)
  File "/usr/src/nginx/naxsi-0.55rc1/nxapi/nxapi/nxtransform.py", line 619, in search
    x = self.es.search(index=self.cfg["elastic"]["index"], doc_type=self.cfg["elastic"]["doctype"], body=esq)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 548, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 94, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 385, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
```

**Comment by buixor** [comment]
Hello !

I believe this was fixed after https://github.com/nbs-system/naxsi/issues/263 thank to @aiwilliams :)
Might you pull 0.55rc1 (current candidate) and confirm you still get the issue ?

**Comment by lookingcloudy** [comment]
Thanks - that's the version I am running.   I added this snippet of code to nxtransform.py and seemed to resolve the problem...a bit of a hack.  This loop was in an endless cycle.  There seemed to be a condition where there were records found to update in elasticsearch, but for some reason were not being updated.  I didn't have to time to track down why.

```
647         total_events = int(str(x["hits"]["total"]))
648         print str(self.grn.format(total_events)) + " items to be tagged ..."
649         size = int(x['hits']['total'])
650         if size > 100:
651             size = size / 10
652         prevcount = -1
653         while count < total_events:
654             if count == prevcount:
655                 print "ENTERED ENDLESS LOOP - BREAKING OUT"
656                 break
657             else:
658                 prevcount = count

```

**Comment by buixor** [comment]
ah thank you :)
would you mind opening a pull request ?

**Comment by jvoisin** [comment]
@lookingcloudy ping ?
