### ISSUE TITLE
UnicodeEncodeError when using nxapi -x flag

### ISSUE THREAD

**Issue by Abukamel** [nbs-system/naxsi#318]
Statistics was running without problem and suddenly after adding new logs to elasticsearch I have encountered this error.

``` python
Traceback (most recent call last):
  File "/usr/bin/nxtool.py", line 283, in <module>
    for e in translate.fetch_top(cfg.cfg["global_filters"], "uri", limit=10):
  File "/usr/lib/python2.7/site-packages/nxapi/nxtransform.py", line 570, in fetch_top
    ret.append('{0} {1}% (total: {2}/{3})'.format(x['key'], round((float(x['doc_count']) / total) * 100, 2), x['doc_count'], total))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 12-19: ordinal not in range(128)
```

Command used : `nxtool.py -c nxapi.json -x`

Note: the website is a right to left site.

**Comment by buixor** [comment]
Hello,

Do you have any sample data that could help me reproduce the bug ?

Regards,

**Comment by hugendudel** [comment]
Hey folks,

I'm facing the same issue.

```
# Top URI(s) :
GET http://localhost:9200/nxapi/events/_search [status:200 request:0.027s]
'/es-ES/productos/registry-fluegas'
# /es-ES/productos/registry-fluegas 0.21% (total:6/2910)
'/fr-CH/Intuitive,+efficace,+s\xef\xbf\xbd\xef\xbf\xbdre+:+la+technique+de+mesure+intelligente+de+Testo/smart-world'
--malformed--
'/cz-CZ/P\xef\xbf\xbd\xef\xbf\xbdehled+veletrh\xef\xbf\xbd\xef\xbf\xbd,+konferenc\xef\xbf\xbd\xef\xbf\xbd,+semin\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd+a+v\xef\xbf\xbd\xef\xbf\xbdstav+2019/veletrhy-konference-seminare'
--malformed--
'/fr-BE/Intuitive,+efficace,+s\xef\xbf\xbd\xef\xbf\xbdre+:+la+technique+de+mesure+intelligente+de+Testo/smart-world'
--malformed--
'/fr-CH/Votre+demande+d\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdoffre/.../highlights'
--malformed--
'/fr-BE/Votre+demande+d\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdoffre/.../highlights'
--malformed--
'/fr-FR/Eviter+les+erreurs+de+mesure+\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd+Conseils+pour+mesurer+correctement/.../coups-de-coeur'
--malformed--
'/de-BE/Pharma-Industrie+(CFR)/applications_pharmacy_and_health_pharmaceutical_industry'
# /de-BE/Pharma-Industrie+(CFR)/applications_pharmacy_and_health_pharmaceutical_industry 0.07% (total:2/2910)
'/de/cover-testo-160-iaq/p/.../highlights'
# /de/cover-testo-160-iaq/p/.../highlights 0.07% (total:2/2910)
'/en-MY/products/.../p/0563-6251'
# /en-MY/products/.../p/0563-6251 0.07% (total:2/2910)
'/en-US/applications/.../datalogger-temperature'
# /en-US/applications/.../datalogger-temperature 0.07% (total:2/2910)
```

I've encoded the uri(x['key']) and printed the value of _list_e[0]_. I'll dive a bit deeper into.

Regards,
Harm
