### ISSUE TITLE
--whitelist --flat-file /tmp/a.log: AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by dorogarcia** [nbs-system/naxsi#382]
Hello,

I am trying to use this tool, but i have an error:

```
git clone https://github.com/nbs-system/nxtool-ng.git
apt install libgeoip-dev libpcre3-dev
cd nxtool-ng
pip install -r ./requirements.txt
wget "https://github.com/maxmind/geoip-api-php/blob/master/tests/data/GeoIPCity.dat?raw=true"
mv GeoIPCity.dat\?raw\=true /usr/share/GeoIP/GeoIPCity.dat
```

```
root@pre:~/nxtool-ng# python nxtool.py --whitelist --flat-file /tmp/a.log
[+] Generating Google analytics rules
Traceback (most recent call last):
  File "nxtool.py", line 153, in <module>
    sys.exit(main())
  File "nxtool.py", line 138, in main
    rules = module.generate_whitelist(source, whitelist)
  File "/root/nxtool-ng/nxtool/whitelists_generators/__init__.py", line 4, in wrapper
    return func(provider, wl)
  File "/root/nxtool-ng/nxtool/whitelists_generators/google_analytics.py", line 17, in generate_whitelist
    ids = provider.get_relevant_ids(['uri', 'ip'])
  File "/root/nxtool-ng/nxtool/log_providers/flat_file.py", line 137, in get_relevant_ids
    for logline in self.get_results():
  File "/root/nxtool-ng/nxtool/log_providers/flat_file.py", line 77, in __get_filtered_logs
    for key, value in log.items():
AttributeError: 'list' object has no attribute 'items'
root@pre:~/nxtool-ng#
```

```
root@pre:~/nxtool-ng# cat /tmp/a.log
2017/06/04 18:33:00 [error] 2264#0: *268 NAXSI_FMT: ip=1.1.1.1&server=pre.aaaaa.com&uri=/&learning=0&total_processed=1&total_blocked=1&zone0=HEADERS&id0=1307&var_name0=cookie, client: 1.1.1.1, server: pre.aaaaa.com, request: "GET / HTTP/1.1", host: "pre.aaaaa.com", referrer: "https://pre.aaaaa.com/"
root@pre:~/nxtool-ng#
```

Thanks for you help :)

**Comment by buixor** [comment]
hello :)

@sabban @dorogarcia : let's move the issue to https://github.com/nbs-system/nxtool-ng ;)

**Comment by sabban** [comment]
This is corrected by now.
