### ISSUE TITLE
Issue with nxtool

### ISSUE THREAD

**Issue by SeSvet** [nbs-system/naxsi#477]
Hi! I'm newby in elasticsearch, so I can't fix this :) I tried to google, but can't understand how to use receipe placed on elasticsearch site. I'm using elasticsearch 5. Problem is only happens when I try to generate whitelist using this command for ex:
 ./nxtool.py -c nxapi.json -s 192.168.16.59 -f --filter 'uri /' --slack

Thanks gor your reply
```

Traceback (most recent call last):
  File "./nxtool.py", line 178, in <module>
    results = translate.full_auto()
  File "/root/naxsi-untagged-afabfc163946baa8036f/nxapi/nxapi/nxtransform.py", line 223, in full_auto
    whitelists = self.gen_wl(template, rule={})
  File "/root/naxsi-untagged-afabfc163946baa8036f/nxapi/nxapi/nxtransform.py", line 712, in gen_wl
    retlist += self.gen_wl(tpl, copy.copy(rule))
  File "/root/naxsi-untagged-afabfc163946baa8036f/nxapi/nxapi/nxtransform.py", line 709, in gen_wl
    unique_vals = self.fetch_uniques(rule, tpl_key)['list']
  File "/root/naxsi-untagged-afabfc163946baa8036f/nxapi/nxapi/nxtransform.py", line 593, in fetch_uniques
    res = self.search(esq)
  File "/root/naxsi-untagged-afabfc163946baa8036f/nxapi/nxapi/nxtransform.py", line 619, in search
    x = self.es.search(index=self.cfg["elastic"]["index"], doc_type=self.cfg["elastic"]["doctype"], body=esq)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/client/__init__.py", line 632, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/connection/http_urllib3.py", line 149, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch5.exceptions.RequestError: TransportError(400, u'search_phase_execution_exception', u'Fielddata is disabled on text fields by default. Set fielddata=true on [id] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.')
```

**Comment by SeSvet** [comment]
I get nxapi from git, not from releases and have no problem :) Sorry for disturb!
